services:
  mysql:
    image: mysql:8.0
    container_name: mysql_upbeat
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - upbeat_network

  backend:
    build: .
    container_name: springboot_upbeat
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_upbeat:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_EXPIRATION_MS: ${APP_JWT_EXPIRATION_MS}
    networks:
      - upbeat_network

volumes:
  mysql_data:

networks:
  upbeat_network:
    driver: bridge
